name: fuzzy_env
dependencies:
  - python=3.9
  - pip
  - pip:
      - streamlit
      - pandas
      - snowflake-connector-python
      - openpyxl  # For Excel file support
      - xlrd      # For older Excel file support
      - chardet   # For encoding detection
